# generated by datamodel-codegen:
#   filename:  _internal
#   timestamp: 2026-03-24T18:43:28+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal, Annotated
from uuid import UUID

from pydantic import (
    AnyUrl,
    NaiveDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class Tag(Enum):
    unsupported_when_assigned = 'unsupported-when-assigned'
    exclusively_hosted_service = 'exclusively-hosted-service'
    disputed = 'disputed'


class CveTag(BaseModel):
    sourceIdentifier: str | None = Field(
        None,
        description='The email address or UUID of the source that contributed the information',
    )
    tags: list[Tag] | None = None


class Type(Enum):
    Primary = 'Primary'
    Secondary = 'Secondary'


class AccessVectorType(Enum):
    NETWORK = 'NETWORK'
    ADJACENT_NETWORK = 'ADJACENT_NETWORK'
    LOCAL = 'LOCAL'


class AccessComplexityType(Enum):
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class AuthenticationType(Enum):
    MULTIPLE = 'MULTIPLE'
    SINGLE = 'SINGLE'
    NONE = 'NONE'


class CiaType(Enum):
    NONE = 'NONE'
    PARTIAL = 'PARTIAL'
    COMPLETE = 'COMPLETE'


class ExploitabilityType(Enum):
    UNPROVEN = 'UNPROVEN'
    PROOF_OF_CONCEPT = 'PROOF_OF_CONCEPT'
    FUNCTIONAL = 'FUNCTIONAL'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class RemediationLevelType(Enum):
    OFFICIAL_FIX = 'OFFICIAL_FIX'
    TEMPORARY_FIX = 'TEMPORARY_FIX'
    WORKAROUND = 'WORKAROUND'
    UNAVAILABLE = 'UNAVAILABLE'
    NOT_DEFINED = 'NOT_DEFINED'


class ReportConfidenceType(Enum):
    UNCONFIRMED = 'UNCONFIRMED'
    UNCORROBORATED = 'UNCORROBORATED'
    CONFIRMED = 'CONFIRMED'
    NOT_DEFINED = 'NOT_DEFINED'


class CollateralDamagePotentialType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    LOW_MEDIUM = 'LOW_MEDIUM'
    MEDIUM_HIGH = 'MEDIUM_HIGH'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class TargetDistributionType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class CiaRequirementType(Enum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class ScoreType(RootModel[confloat(ge=0.0, le=10.0)]):
    root: confloat(ge=0.0, le=10.0)


class AttackVectorType(Enum):
    NETWORK = 'NETWORK'
    ADJACENT_NETWORK = 'ADJACENT_NETWORK'
    LOCAL = 'LOCAL'
    PHYSICAL = 'PHYSICAL'


class ModifiedAttackVectorType(Enum):
    NETWORK = 'NETWORK'
    ADJACENT_NETWORK = 'ADJACENT_NETWORK'
    LOCAL = 'LOCAL'
    PHYSICAL = 'PHYSICAL'
    NOT_DEFINED = 'NOT_DEFINED'


class AttackComplexityType(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'


class ModifiedAttackComplexityType(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'
    NOT_DEFINED = 'NOT_DEFINED'


class PrivilegesRequiredType(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'
    NONE = 'NONE'


class ModifiedPrivilegesRequiredType(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'
    NONE = 'NONE'
    NOT_DEFINED = 'NOT_DEFINED'


class UserInteractionType(Enum):
    NONE = 'NONE'
    REQUIRED = 'REQUIRED'


class ModifiedUserInteractionType(Enum):
    NONE = 'NONE'
    REQUIRED = 'REQUIRED'
    NOT_DEFINED = 'NOT_DEFINED'


class ScopeType(Enum):
    UNCHANGED = 'UNCHANGED'
    CHANGED = 'CHANGED'


class ModifiedScopeType(Enum):
    UNCHANGED = 'UNCHANGED'
    CHANGED = 'CHANGED'
    NOT_DEFINED = 'NOT_DEFINED'


class CiaTypeModel(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    HIGH = 'HIGH'


class ModifiedCiaType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class ExploitCodeMaturityType(Enum):
    UNPROVEN = 'UNPROVEN'
    PROOF_OF_CONCEPT = 'PROOF_OF_CONCEPT'
    FUNCTIONAL = 'FUNCTIONAL'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class ConfidenceType(Enum):
    UNKNOWN = 'UNKNOWN'
    REASONABLE = 'REASONABLE'
    CONFIRMED = 'CONFIRMED'
    NOT_DEFINED = 'NOT_DEFINED'


class SeverityType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    CRITICAL = 'CRITICAL'


class AttackVectorTypeModel(Enum):
    NETWORK = 'NETWORK'
    ADJACENT = 'ADJACENT'
    LOCAL = 'LOCAL'
    PHYSICAL = 'PHYSICAL'


class ModifiedAttackVectorTypeModel(Enum):
    NETWORK = 'NETWORK'
    ADJACENT = 'ADJACENT'
    LOCAL = 'LOCAL'
    PHYSICAL = 'PHYSICAL'
    NOT_DEFINED = 'NOT_DEFINED'


class AttackRequirementsType(Enum):
    NONE = 'NONE'
    PRESENT = 'PRESENT'


class ModifiedAttackRequirementsType(Enum):
    NONE = 'NONE'
    PRESENT = 'PRESENT'
    NOT_DEFINED = 'NOT_DEFINED'


class UserInteractionTypeModel(Enum):
    NONE = 'NONE'
    PASSIVE = 'PASSIVE'
    ACTIVE = 'ACTIVE'


class ModifiedUserInteractionTypeModel(Enum):
    NONE = 'NONE'
    PASSIVE = 'PASSIVE'
    ACTIVE = 'ACTIVE'
    NOT_DEFINED = 'NOT_DEFINED'


class VulnCiaType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    HIGH = 'HIGH'


class ModifiedVulnCiaType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class SubCiaType(Enum):
    NONE = 'NONE'
    LOW = 'LOW'
    HIGH = 'HIGH'


class ModifiedSubCType(Enum):
    NEGLIGIBLE = 'NEGLIGIBLE'
    LOW = 'LOW'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class ModifiedSubIaType(Enum):
    NEGLIGIBLE = 'NEGLIGIBLE'
    LOW = 'LOW'
    HIGH = 'HIGH'
    SAFETY = 'SAFETY'
    NOT_DEFINED = 'NOT_DEFINED'


class ExploitMaturityType(Enum):
    UNREPORTED = 'UNREPORTED'
    PROOF_OF_CONCEPT = 'PROOF_OF_CONCEPT'
    ATTACKED = 'ATTACKED'
    NOT_DEFINED = 'NOT_DEFINED'


class SafetyType(Enum):
    NEGLIGIBLE = 'NEGLIGIBLE'
    PRESENT = 'PRESENT'
    NOT_DEFINED = 'NOT_DEFINED'


class AutomatableType(Enum):
    NO = 'NO'
    YES = 'YES'
    NOT_DEFINED = 'NOT_DEFINED'


class RecoveryType(Enum):
    AUTOMATIC = 'AUTOMATIC'
    USER = 'USER'
    IRRECOVERABLE = 'IRRECOVERABLE'
    NOT_DEFINED = 'NOT_DEFINED'


class ValueDensityType(Enum):
    DIFFUSE = 'DIFFUSE'
    CONCENTRATED = 'CONCENTRATED'
    NOT_DEFINED = 'NOT_DEFINED'


class VulnerabilityResponseEffortType(Enum):
    LOW = 'LOW'
    MODERATE = 'MODERATE'
    HIGH = 'HIGH'
    NOT_DEFINED = 'NOT_DEFINED'


class ProviderUrgencyType(Enum):
    CLEAR = 'CLEAR'
    GREEN = 'GREEN'
    AMBER = 'AMBER'
    RED = 'RED'
    NOT_DEFINED = 'NOT_DEFINED'


class NoneScoreType(RootModel[confloat(ge=0.0, le=0.0)]):
    root: confloat(ge=0.0, le=0.0)


class LowScoreType(RootModel[confloat(ge=0.1, le=3.9, multiple_of=0.1)]):
    root: confloat(ge=0.1, le=3.9, multiple_of=0.1)


class MediumScoreType(RootModel[confloat(ge=4.0, le=6.9, multiple_of=0.1)]):
    root: confloat(ge=4.0, le=6.9, multiple_of=0.1)


class HighScoreType(RootModel[confloat(ge=7.0, le=8.9, multiple_of=0.1)]):
    root: confloat(ge=7.0, le=8.9, multiple_of=0.1)


class CriticalScoreType(RootModel[confloat(ge=9.0, le=10.0, multiple_of=0.1)]):
    root: confloat(ge=9.0, le=10.0, multiple_of=0.1)


class NoneSeverityType(RootModel[Literal['NONE']]):
    root: Literal['NONE']


class LowSeverityType(RootModel[Literal['LOW']]):
    root: Literal['LOW']


class MediumSeverityType(RootModel[Literal['MEDIUM']]):
    root: Literal['MEDIUM']


class HighSeverityType(RootModel[Literal['HIGH']]):
    root: Literal['HIGH']


class CriticalSeverityType(RootModel[Literal['CRITICAL']]):
    root: Literal['CRITICAL']


class CveId(RootModel[constr(pattern=r'^CVE-[0-9]{4}-[0-9]{4,}$')]):
    root: constr(pattern=r'^CVE-[0-9]{4}-[0-9]{4,}$')


class LangString(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lang: str
    value: constr(max_length=4096)


class Reference(BaseModel):
    url: AnyUrl
    source: str | None = None
    tags: list[str] | None = None


class VendorComment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    organization: str
    comment: str
    lastModified: NaiveDatetime

class CWE(BaseModel):
    id: Annotated[str, Field(pattern=r"^\d+$")]
    name: str

    def __str__(self):
        return f"CWE-{self.id} - {self.name}"

class Weakness(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str
    type: str
    description: list[LangString] = Field(..., min_length=0)
    cwe: CWE | None = None

    def set_cwe(self, cwe: CWE):
        self.cwe = cwe

class Operator(Enum):
    AND = 'AND'
    OR = 'OR'


class CpeMatch(BaseModel):
    vulnerable: bool
    criteria: str
    matchCriteriaId: UUID
    versionStartExcluding: str | None = None
    versionStartIncluding: str | None = None
    versionEndExcluding: str | None = None
    versionEndIncluding: str | None = None


class DefSubscore(RootModel[confloat(ge=0.0, le=10.0)]):
    root: confloat(ge=0.0, le=10.0) = Field(..., description='CVSS subscore.')


class Node(BaseModel):
    operator: Operator
    negate: bool | None = None
    cpeMatch: list[CpeMatch]


class CvssV2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str
    type: Type
    cvssData: Field0
    baseSeverity: str | None = None
    exploitabilityScore: DefSubscore | None = None
    impactScore: DefSubscore | None = None
    acInsufInfo: bool | None = None
    obtainAllPrivilege: bool | None = None
    obtainUserPrivilege: bool | None = None
    obtainOtherPrivilege: bool | None = None
    userInteractionRequired: bool | None = None


class CvssV30(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str
    type: Type
    cvssData: Field0_1
    exploitabilityScore: DefSubscore | None = None
    impactScore: DefSubscore | None = None

    def get_base_score(self):
        return self.cvssData.baseScore.root

class CvssV31(CvssV30):
    cvssData: Field1


class CvssV40(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str
    type: Type
    cvssData: Field0Model6


class Config(BaseModel):
    operator: Operator | None = None
    negate: bool | None = None
    nodes: list[Node]


class Metrics(BaseModel):
    cvssMetricV40: list[CvssV40] | None = Field(None, description='CVSS V4.0 score.')
    cvssMetricV31: list[CvssV31] | None = Field(None, description='CVSS V3.1 score.')
    cvssMetricV30: list[CvssV30] | None = Field(None, description='CVSS V3.0 score.')
    cvssMetricV2: list[CvssV2] | None = Field(None, description='CVSS V2.0 score.')
    
    def get_v3_base_score(self) -> float | None:
        subject = None
        if self.cvssMetricV31:
            subject = self.cvssMetricV31
        elif self.cvssMetricV30:
            subject = self.cvssMetricV30
        else:
            return None
        return subject[0].get_base_score()


class CveItem(BaseModel):
    id: CveId
    sourceIdentifier: str | None = None
    vulnStatus: str | None = None
    published: NaiveDatetime
    lastModified: NaiveDatetime
    evaluatorComment: str | None = None
    evaluatorSolution: str | None = None
    evaluatorImpact: str | None = None
    cisaExploitAdd: date | None = None
    cisaActionDue: date | None = None
    cisaRequiredAction: str | None = None
    cisaVulnerabilityName: str | None = None
    cveTags: list[CveTag] | None = None
    descriptions: list[LangString] = Field(..., min_length=1)
    references: list[Reference]
    metrics: Metrics | None = Field(
        None, description='Metric scores for a vulnerability as found on NVD.'
    )
    weaknesses: list[Weakness] | None = None
    configurations: list[Config] | None = None
    vendorComments: list[VendorComment] | None = None
    
    def get_description(self) -> str:
        for desc in self.descriptions:
            if desc.lang == 'en':
                return desc.value
        print('Failed to find english description, retuning first entry')
        return self.descriptions[0].value


class DefCveItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cve: CveItem


class JsonSchemaForNvdVulnerabilityDataApiVersion223(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resultsPerPage: int
    startIndex: int
    totalResults: int
    format: str
    version: str
    timestamp: NaiveDatetime
    vulnerabilities: list[DefCveItem] = Field(..., description='NVD feed array of CVE')


class Version(Enum):
    field_2_0 = '2.0'


class Field0(BaseModel):
    version: Version = Field(..., description='CVSS Version')
    vectorString: constr(
        pattern=r'^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$'
    )
    accessVector: AccessVectorType | None = None
    accessComplexity: AccessComplexityType | None = None
    authentication: AuthenticationType | None = None
    confidentialityImpact: CiaType | None = None
    integrityImpact: CiaType | None = None
    availabilityImpact: CiaType | None = None
    baseScore: ScoreType
    exploitability: ExploitabilityType | None = None
    remediationLevel: RemediationLevelType | None = None
    reportConfidence: ReportConfidenceType | None = None
    temporalScore: ScoreType | None = None
    collateralDamagePotential: CollateralDamagePotentialType | None = None
    targetDistribution: TargetDistributionType | None = None
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    environmentalScore: ScoreType | None = None


class Version_1(Enum):
    field_3_0 = '3.0'


class VersionModel(Enum):
    field_3_1 = '3.1'


class Field0_1(BaseModel):
    version: Version_1 = Field(..., description='CVSS Version')
    vectorString: constr(
        pattern=r'^CVSS:3[.]0/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$'
    )
    attackVector: AttackVectorType | None = None
    attackComplexity: AttackComplexityType | None = None
    privilegesRequired: PrivilegesRequiredType | None = None
    userInteraction: UserInteractionType | None = None
    scope: ScopeType | None = None
    confidentialityImpact: CiaTypeModel | None = None
    integrityImpact: CiaTypeModel | None = None
    availabilityImpact: CiaTypeModel | None = None
    baseScore: ScoreType
    baseSeverity: SeverityType
    exploitCodeMaturity: ExploitCodeMaturityType | None = None
    remediationLevel: RemediationLevelType | None = None
    reportConfidence: ConfidenceType | None = None
    temporalScore: ScoreType | None = None
    temporalSeverity: SeverityType | None = None
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    modifiedAttackVector: ModifiedAttackVectorType | None = None
    modifiedAttackComplexity: ModifiedAttackComplexityType | None = None
    modifiedPrivilegesRequired: ModifiedPrivilegesRequiredType | None = None
    modifiedUserInteraction: ModifiedUserInteractionType | None = None
    modifiedScope: ModifiedScopeType | None = None
    modifiedConfidentialityImpact: ModifiedCiaType | None = None
    modifiedIntegrityImpact: ModifiedCiaType | None = None
    modifiedAvailabilityImpact: ModifiedCiaType | None = None
    environmentalScore: ScoreType | None = None
    environmentalSeverity: SeverityType | None = None


class Field1(BaseModel):
    version: VersionModel = Field(..., description='CVSS Version')
    vectorString: constr(
        pattern=r'^CVSS:3[.]1/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$'
    )
    attackVector: AttackVectorType | None = None
    attackComplexity: AttackComplexityType | None = None
    privilegesRequired: PrivilegesRequiredType | None = None
    userInteraction: UserInteractionType | None = None
    scope: ScopeType | None = None
    confidentialityImpact: CiaTypeModel | None = None
    integrityImpact: CiaTypeModel | None = None
    availabilityImpact: CiaTypeModel | None = None
    baseScore: ScoreType
    baseSeverity: SeverityType
    exploitCodeMaturity: ExploitCodeMaturityType | None = None
    remediationLevel: RemediationLevelType | None = None
    reportConfidence: ConfidenceType | None = None
    temporalScore: ScoreType | None = None
    temporalSeverity: SeverityType | None = None
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    modifiedAttackVector: ModifiedAttackVectorType | None = None
    modifiedAttackComplexity: ModifiedAttackComplexityType | None = None
    modifiedPrivilegesRequired: ModifiedPrivilegesRequiredType | None = None
    modifiedUserInteraction: ModifiedUserInteractionType | None = None
    modifiedScope: ModifiedScopeType | None = None
    modifiedConfidentialityImpact: ModifiedCiaType | None = None
    modifiedIntegrityImpact: ModifiedCiaType | None = None
    modifiedAvailabilityImpact: ModifiedCiaType | None = None
    environmentalScore: ScoreType | None = None
    environmentalSeverity: SeverityType | None = None


class Version_2(Enum):
    field_4_0 = '4.0'


class Field0_2(BaseModel):
    environmentalScore: NoneScoreType | None = None
    environmentalSeverity: NoneSeverityType | None = None


class Field0Model(BaseModel):
    environmentalScore: LowScoreType | None = None
    environmentalSeverity: LowSeverityType | None = None


class Field0Model1(BaseModel):
    environmentalScore: MediumScoreType | None = None
    environmentalSeverity: MediumSeverityType | None = None


class Field0Model2(BaseModel):
    environmentalScore: HighScoreType | None = None
    environmentalSeverity: HighSeverityType | None = None


class Field0Model3(BaseModel):
    environmentalScore: CriticalScoreType | None = None
    environmentalSeverity: CriticalSeverityType | None = None


class Field0Model4(BaseModel):
    version: Version_2 = Field(..., description='CVSS Version')
    vectorString: constr(
        pattern=r'^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$'
    )
    attackVector: AttackVectorTypeModel | None = None
    attackComplexity: AttackComplexityType | None = None
    attackRequirements: AttackRequirementsType | None = None
    privilegesRequired: PrivilegesRequiredType | None = None
    userInteraction: UserInteractionTypeModel | None = None
    vulnConfidentialityImpact: VulnCiaType | None = None
    vulnIntegrityImpact: VulnCiaType | None = None
    vulnAvailabilityImpact: VulnCiaType | None = None
    subConfidentialityImpact: SubCiaType | None = None
    subIntegrityImpact: SubCiaType | None = None
    subAvailabilityImpact: SubCiaType | None = None
    exploitMaturity: ExploitMaturityType | None = 'NOT_DEFINED'
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    modifiedAttackVector: ModifiedAttackVectorTypeModel | None = 'NOT_DEFINED'
    modifiedAttackComplexity: ModifiedAttackComplexityType | None = None
    modifiedAttackRequirements: ModifiedAttackRequirementsType | None = 'NOT_DEFINED'
    modifiedPrivilegesRequired: ModifiedPrivilegesRequiredType | None = None
    modifiedUserInteraction: ModifiedUserInteractionTypeModel | None = 'NOT_DEFINED'
    modifiedVulnConfidentialityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedVulnIntegrityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedVulnAvailabilityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedSubConfidentialityImpact: ModifiedSubCType | None = 'NOT_DEFINED'
    modifiedSubIntegrityImpact: ModifiedSubIaType | None = 'NOT_DEFINED'
    modifiedSubAvailabilityImpact: ModifiedSubIaType | None = 'NOT_DEFINED'
    Safety: SafetyType | None = 'NOT_DEFINED'
    Automatable: AutomatableType | None = 'NOT_DEFINED'
    Recovery: RecoveryType | None = 'NOT_DEFINED'
    valueDensity: ValueDensityType | None = 'NOT_DEFINED'
    vulnerabilityResponseEffort: VulnerabilityResponseEffortType | None = 'NOT_DEFINED'
    providerUrgency: ProviderUrgencyType | None = 'NOT_DEFINED'


class Field0Model5(Field0_2, Field0Model4):
    version: Version_2 = Field(..., description='CVSS Version')
    vectorString: constr(
        pattern=r'^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$'
    )
    attackVector: AttackVectorTypeModel | None = None
    attackComplexity: AttackComplexityType | None = None
    attackRequirements: AttackRequirementsType | None = None
    privilegesRequired: PrivilegesRequiredType | None = None
    userInteraction: UserInteractionTypeModel | None = None
    vulnConfidentialityImpact: VulnCiaType | None = None
    vulnIntegrityImpact: VulnCiaType | None = None
    vulnAvailabilityImpact: VulnCiaType | None = None
    subConfidentialityImpact: SubCiaType | None = None
    subIntegrityImpact: SubCiaType | None = None
    subAvailabilityImpact: SubCiaType | None = None
    exploitMaturity: ExploitMaturityType | None = 'NOT_DEFINED'
    confidentialityRequirement: CiaRequirementType | None = None
    integrityRequirement: CiaRequirementType | None = None
    availabilityRequirement: CiaRequirementType | None = None
    modifiedAttackVector: ModifiedAttackVectorTypeModel | None = 'NOT_DEFINED'
    modifiedAttackComplexity: ModifiedAttackComplexityType | None = None
    modifiedAttackRequirements: ModifiedAttackRequirementsType | None = 'NOT_DEFINED'
    modifiedPrivilegesRequired: ModifiedPrivilegesRequiredType | None = None
    modifiedUserInteraction: ModifiedUserInteractionTypeModel | None = 'NOT_DEFINED'
    modifiedVulnConfidentialityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedVulnIntegrityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedVulnAvailabilityImpact: ModifiedVulnCiaType | None = 'NOT_DEFINED'
    modifiedSubConfidentialityImpact: ModifiedSubCType | None = 'NOT_DEFINED'
    modifiedSubIntegrityImpact: ModifiedSubIaType | None = 'NOT_DEFINED'
    modifiedSubAvailabilityImpact: ModifiedSubIaType | None = 'NOT_DEFINED'
    Safety: SafetyType | None = 'NOT_DEFINED'
    Automatable: AutomatableType | None = 'NOT_DEFINED'
    Recovery: RecoveryType | None = 'NOT_DEFINED'
    valueDensity: ValueDensityType | None = 'NOT_DEFINED'
    vulnerabilityResponseEffort: VulnerabilityResponseEffortType | None = 'NOT_DEFINED'
    providerUrgency: ProviderUrgencyType | None = 'NOT_DEFINED'


class Field0Model6(RootModel[Field0Model5]):
    root: Field0Model5 = Field(
        ..., title='JSON Schema for Common Vulnerability Scoring System version 4.0'
    )
