# generated by datamodel-codegen:
#   filename:  cpe_api_json_2.0.schema
#   timestamp: 2026-03-24T20:18:40+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class DefTitle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    lang: str


class Type(Enum):
    Advisory = 'Advisory'
    Change_Log = 'Change Log'
    Product = 'Product'
    Project = 'Project'
    Vendor = 'Vendor'
    Version = 'Version'


class DefReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: constr(
        pattern=r'^([A-Za-z][A-Za-z0-9+.-]+):(\/\/([^@]+@)?([A-Za-z0-9.\-_~]+)(:\d+)?)?((?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@])+(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@])*)*|(?:\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'()*+,;=:@])+)*)?(\?(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@]|[/?])*)?(\#(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&\'\[\]()*+,;=:@]|[/?])*)?$'
    )
    type: Type | None = None


class DeprecatedByItem(BaseModel):
    cpeName: str | None = None
    cpeNameId: UUID | None = None


class Deprecate(BaseModel):
    cpeName: str | None = None
    cpeNameId: UUID | None = None


class Cpe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecated: bool
    cpeName: str
    cpeNameId: UUID
    created: AwareDatetime
    lastModified: AwareDatetime
    titles: list[DefTitle] | None = None
    refs: list[DefReference] | None = None
    deprecatedBy: list[DeprecatedByItem] | None = None
    deprecates: list[Deprecate] | None = None


class DefCpe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpe: Cpe


class JsonSchemaForNvdCommonProductEnumerationCpeApiVersion20(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resultsPerPage: int
    startIndex: int
    totalResults: int
    format: str
    version: str
    timestamp: AwareDatetime
    products: list[DefCpe] = Field(..., description='NVD feed array of CPE')
