#!/usr/bin/env bash
#
# Copyright (c) 2025 Riverside Research.
# LGPL-3; See LICENSE.txt in the repo root for details.

set -e 

REAL_CLANG="/usr/bin/clang"

# clang lowers mem* libc funtions into llvm intrinsics with additional metadata
# for optimization we want our CVEAssert sanitizers to see the original libc
# functions, so we ask clang to skip the special handling
# Ideally, we would only do that for vulnerable functions, but that requires behavior changes in clang or modifing source code
FLAGS=(
    -Wextra
    -Wall
    -fno-builtin-memcpy
    -fno-builtin-memmove
    -fno-builtin-memset
    -fpass-plugin=/build-resolve/resolve-cveassert/build/libCVEAssert.so
)

# Debugging 
echo "[resolvecc] $@" >&2

if [[ "$1" == "--version" ]]; then
    exec "$REAL_CLANG" "$@"
fi

exec "$REAL_CLANG" $FLAGS "$@" 