#!/usr/bin/env bash
#
# Copyright (c) 2025 Riverside Research.
# LGPL-3; See LICENSE.txt in the repo root for details.

set -e
# set -x for debugging

# Paths for clang and libresolve rtlib
REAL_CLANG="/usr/bin/clang"
LIBRESOLVE_PATH="libresolve/target/release"

# DEBUGGING: Writes each compiler invocation to stderr 
echo "[resolvecc] $@" >&2

# clang lowers mem* libc funtions into llvm intrinsics with additional metadata
# for optimization we want our CVEAssert sanitizers to see the original libc
# functions, so we ask clang to skip the special handling
# Ideally, we would only do that for vulnerable functions, but that requires behavior changes in clang or modifying source code
COMPTIME_FLAGS=(
    -fno-builtin-memcpy
    -fno-builtin-memmove
    -fno-builtin-memset
    -fpass-plugin=/opt/resolve/resolve-cveassert/build/libCVEAssert.so
)

RUNTIME_FLAGS=(
    -L/opt/resolve/"$LIBRESOLVE_PATH"
    -lresolve
    -Wl,-rpath=/opt/resolve/"$LIBRESOLVE_PATH"
)

# Ensure --version flag works with wrapper
if [[ "$1" == "--version" ]]; then
    exec "$REAL_CLANG" "$@"
fi

# Variable tells resolvecc whether to link libresolve or not
LINK_LIBRESOLVE=true


# resolvecc -fcve-assert=<vuln.json> <flags> <source>
RESOLVE_LABEL_CVE=""
NEW_ARGS=()
args=("$@")

for ((i=0; i<${#args[@]}; i++)); do
    
    arg="${args[$i]}"

    if [[ "$arg" == "-c" || "$arg" == "-S" || "$arg" == "-E" ]]; then
        LINK_LIBRESOLVE=false
    fi

    if [[ "$arg" == "-fcve-assert" ]]; then
        file_path="${args[$((i + 1))]}"
        if [[ ! -f "$file_path" ]]; then
            echo "[resolvecc]: ERROR '$file_path' could not be found!"
            exit 1
        fi 

        RESOLVE_LABEL_CVE="$file_path"
        i=$((i + 2)) # Skip over flag and file path, clang does not understand these flags. 
    else 
        NEW_ARGS+=("$arg")
    fi
done 

if $LINKING; then
    RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
    exec "$REAL_CLANG" \
        "${COMPTIME_FLAGS[@]}" \
        "${NEW_ARGS[@]}" \
        "${RUNTIME_FLAGS[@]}"
else 
    RESOLVE_LABEL_CVE="$RESOLVE_LABEL_CVE"\
    exec "$REAL_CLANG" \
        "${COMPTIME_FLAGS[@]}" \
        "${NEW_ARGS[@]}"
fi