# Copyright (c) 2025 Riverside Research.
# LGPL-3; See LICENSE.txt in the repo root for details.

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from .agent import run_critique, run_prompt
from .utils import prepare_output_path, require_file


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    prog = os.path.basename(sys.argv[0])

    parser = argparse.ArgumentParser(
        description="Run a reachability analysis pipeline on conditions generated by improve_CVE.py. The pipeline performs an initial analysis followed by a challenge/revise pass. All intermediate artifacts are written under a unique /tmp workspace and final results are copied to output_path.",
        epilog=f"""Examples:
  {prog} codex cve.json out/improve_cve out/reachability
  {prog} claude cve.json out/improve_cve out/reachability""",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "agent",
        choices=("claude", "codex", "opencode"),
        help="Coding agent backend to execute prompts with.",
    )
    parser.add_argument(
        "cve_path",
        type=Path,
        help="Path to the input CVE file.",
    )
    parser.add_argument(
        "improve_cve_path",
        type=Path,
        help="Output directory from improve_CVE.py containing condition documents.",
    )
    parser.add_argument(
        "output_path",
        type=Path,
        help="Destination directory for final artifacts.",
    )
    parser.add_argument(
        "--model",
        help="Optional model override passed through to the selected agent CLI.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output_path if it already exists.",
    )
    return parser.parse_args(argv)


def run(
    agent: str,
    cve_path: Path,
    improve_cve_path: Path,
    output_path: Path,
    overwrite: bool,
    model: str | None = None,
) -> int:
    cve = cve_path.read_text()

    if not improve_cve_path.is_dir():
        raise RuntimeError(f"improve_cve_path is not a directory: {improve_cve_path}")

    necessary_conditions_path = improve_cve_path / "necessary_conditions"
    sufficient_conditions_path = improve_cve_path / "sufficient_conditions"
    if not necessary_conditions_path.is_dir():
        raise RuntimeError(f"missing directory: {necessary_conditions_path}")
    if not sufficient_conditions_path.is_dir():
        raise RuntimeError(f"missing directory: {sufficient_conditions_path}")

    if not any(necessary_conditions_path.glob("NC_*.md")):
        print(f"warning: no NC_*.md files in {necessary_conditions_path}")
    if not any(sufficient_conditions_path.glob("SC_*.md")):
        print(f"warning: no SC_*.md files in {sufficient_conditions_path}")

    prepare_output_path(output_path, overwrite)

    tmp_path = Path(tempfile.mkdtemp(dir="/tmp", prefix="reachability_"))
    print(f"Using temporary workspace: {tmp_path}")

    output_root = tmp_path / "output"
    output_root.mkdir(parents=True, exist_ok=True)

    reachability_path = output_root / "reachability.md"
    critique_path = tmp_path / "critique_scratch"
    critique_path.mkdir()

    ############################################################################
    # REACHABILITY ANALYSIS
    ############################################################################

    analyze_prompt = f"""
# CVE

{cve}

`{necessary_conditions_path}/` contains a collection of necessary conditions for triggering the above CVE. `{sufficient_conditions_path}/` contains a collection of sufficient conditions for triggering the above CVE.

# Your task

1) Determine if all of the necessary conditions are simultaneously satisfiable via user/client input to this project. If so, continue. If not (one or more of the necessary conditions is definitely not satisfiable), report the CVE as 'not triggerable', explain why not, and end the analysis.
2) Determine if any of the sufficient conditions are definitely satisfiable via user/client input. If so, report the CVE as 'triggerable' and explain how. If not, report the CVE as inconclusive.

Save a report in `{reachability_path}`.

A condition is "necessary" if there is no way to trigger the bug without satisfying the condition. I.e., if the bug is triggered, the condition must be true. A condition is "sufficient" if satisfying the condition guarantees that the bug will be triggered.

The CVE is triggerable only if a sufficient condition can be satisfied. The CVE is not triggerable only if a necessary condition can't be satisfied. Otherwise the CVE is inconclusive.

If the only satisfiable sufficient condition(s) are machine-dependent (e.g., x86 or ARM) or depend on unreliable compiler features such as "typical" results of undefined behavior, the CVE is inconclusive.
"""
    run_prompt(agent, analyze_prompt, model=model)
    require_file(reachability_path, "reachability analysis")

    ############################################################################
    # REACHABILITY CRITIQUE
    ############################################################################

    reachability_content = reachability_path.read_text()

    critique_preamble = f"""# CVE

{cve}

# Reachability analysis

{reachability_content}"""

    run_critique(
        agent,
        preamble=critique_preamble,
        negation="The reachability analysis is incorrect. Your task is to determine what errors it contains and how the conclusion should change.",
        tmp_dir=critique_path,
        output_path=reachability_path,
        model=model,
    )
    require_file(reachability_path, "reachability critique")

    ############################################################################
    # INPUT SYNTHESIS AND CONCLUSION
    ############################################################################

    final_prompt = f"""
`{reachability_path}` contains a reachability analysis of a CVE possibly affecting this project. Your tasks:
1) If `{reachability_path}` concludes that the CVE is triggerable, synthesize an input that triggers it and verify that it works. If triggerability is inconclusive, try to synthesize an input and see if it works (and if it fails still report the result as inconclusive). If `{reachability_path}` concludes that the CVE is not triggerable, skip this step. Don't second-guess the conclusion.
2) Write a one-paragraph summary of the conclusion to `{output_root}/conclusion.md`.

If you synthesize an input, ensure that it will work on any realistic system if possible. E.g., if the exploit depends on resource exhaustion then make it work on a system that has a large amount of that resource.

Put any files you create in `{output_root}/input-synthesis/`. If a triggering input is synthesized, include an explanation of how it was synthesized and how to test that it works. Don't delete any scripts/programs that were used to generate the input.
"""
    run_prompt(agent, final_prompt, model=model)
    require_file(output_root / "conclusion.md", "final conclusion")

    ############################################################################
    # COPY FINAL RESULTS TO OUTPUT PATH
    ############################################################################

    shutil.copytree(output_root, output_path)

    return 0


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        return run(
            agent=args.agent,
            cve_path=args.cve_path,
            improve_cve_path=args.improve_cve_path,
            output_path=args.output_path,
            overwrite=args.overwrite,
            model=args.model,
        )
    except subprocess.CalledProcessError as exc:
        print(f"agent failed with exit code {exc.returncode}")
        return exc.returncode if exc.returncode != 0 else 1
    except (RuntimeError, ValueError) as exc:
        print(exc)
        return -1


if __name__ == "__main__":
    raise SystemExit(main())
