name: Build and Publish Remediated Analyze-Image

on: 
  push:
    branches:
      - feature/add-more-examples
    paths:
      - examples/eboss_eval/hacky_trigger.log

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Resolve Docker Image
        run: docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Checkout Resolve Builder Docker Image
        run: docker pull ghcr.io/${{ github.repository_owner }}/resolve/resolve-builder:latest

      - name: Re-tag docker images
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest resolve:latest
          docker tag ghcr.io/${{ github.repository_owner }}/resolve/resolve-builder:latest resolve-builder:latest

      - name: Checkout ebossproject/analyze-images-v2
        uses: actions/checkout@v5
        with:
          repository: ebossproject/analyze-images-v2

      - name: Checkout remediated build files
        uses: actions/checkout@v5
        with:
          path: .
          sparse-checkout: |
            examples/eboss_eval/src/analyze-images/analyze-image-remediated.dockerfile
            examples/eboss_eval/src/analyze-images/analyze-image-vulns.json
          sparse-checkout-cone-mode: false

      - name: Rename files for ease of integration
        run: |
          mv examples/eboss_eval/src/analyze-images/analyze-image-remediated.dockerfile Dockerfile
          mv examples/eboss_eval/src/analyze-images/analyze-image-vulns.json vulnerabilities.json
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/analyze-image/server-remediated:latest
