name: resolve CI

on:
  push: 
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install deps
        run: make install-deps
      - name: Build
        run: make build-with-klee
      - name: Install
        run: make install-with-klee
      - name: Test
        run: make test-with-klee
      - name: Check
        run: make check-with-klee
      - name: Build Examples
        run: ./examples/misc/openssl.sh
